AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      NotificationConfiguration: # Integrates the events with EventBridge
        EventBridgeConfiguration:
          EventBridgeEnabled: true
  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 256
      Architectures: ["arm64"] 
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 30
      CodeUri: target/lambda/aws_image_archiver/
      Policies:
        S3CrudPolicy:
          BucketName: !Ref Bucket
      Events:
        Trigger:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                  - !Ref Bucket
                object:
                  key:
                    - prefix: "archive/"
Outputs:
  BucketName:
    Value: !Ref Bucket
    Description: Name of the bucket